services:
  mysql:
    image: mysql:9.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=pawcareclinic
      - MYSQL_PASSWORD=pawcareclinic
      - MYSQL_DATABASE=pawcareclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  postgres:
    image: postgres:18.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pawcareclinic
      - POSTGRES_USER=pawcareclinic
      - POSTGRES_DB=pawcareclinic
